### ISSUE TITLE
Notification re: new path names

### ISSUE THREAD

**Issue by JosephLalli** [human-pangenomics/hpp_pangenome_resources#18]
Are the v1.1 graphs supposed to have new names for the reference paths?

In the past I was surjecting into reference paths (aka GRCh38 and CHM13v2 named ${reference}.{contig}, but the Right now I can't surject to the old path "CHM13v2.chr20", for example. The new path name is "CHM13#0#chr20".

While that is probably as it should be,* you might want to let users know about the change.

-Joe

*I get it, adding the #0# specifies the reference allele and brings the reference path names up to the same spec as the rest of the paths, thus allowing for better tool interoperability.

**Comment by glennhickey** [comment]
Yeah, the name change of the vg paths is necessary to be compatible with current versions of vg.  I've added a note in #19 -- thanks for bringing this up.
