### ISSUE TITLE
Segfault with odgi when trying to convert chrom graphs from mgc

### ISSUE THREAD

**Issue by dubssieg** [human-pangenomics/hpp_pangenome_resources#25]
Greetings, and thanks for this work.

The chromosome graphs for minigraph-cactus are available both in `.vg` and `.og` format, but as far as I know, only the `.og` version is the full, non-clipped, non-filtered graph.
However, when I try to do any manipulation on them using odgi (0.8.6) like converting those to `.gfa` using `odgi view -g -i $INPUT > $OUTPUT`, I get a segfault in return.
Is there any place where I can find the full graphs from mgc in `.gfa`, or a `.og` that can be read by odgi?

Thanks in advance.

**Comment by glennhickey** [comment]
I just ran `odgi view` on https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.1-mc-grch38/hprc-v1.1-mc-grch38.chroms/chrY.full.og using both odgi version 0.8.4 and 0.8.6 and it ran fine.  Can you tell me exactly which file you are having trouble with?

**Comment by dubssieg** [comment]
Just tried on the file you provided, got a core dump as well.
I guess it is an issue with my installation of odgi, will investigate and let know if I find any workaround/fix for anyone having the same issue.

Thanks a lot for your quick reply!

**Comment by dubssieg** [comment]
Tried on another machine, it seems the issue is between Fedora (or at least my machine) and odgi.
The only strange point is that I never had such issues with odgi on any other graph.
Worked just fine on another system, so closing! Have a nice day.
