### ISSUE TITLE
Masked sequence, coordinate confusion

### ISSUE THREAD

**Issue by dduchen** [human-pangenomics/hpp_pangenome_resources#7]
Hello,
I just wanted to confirm that the mask-related BED files for the minigraph/CACTUS graph are correct, or if they have been switched, as the coordinates within the [hprc-v1.0-mc-grch38.clipped-intervals.bed.gz](https://s3-us-west-2.amazonaws.com/human-pangenomics/pangenomes/freeze/freeze1/minigraph-cactus/hprc-v1.0-mc-grch38.clipped-intervals.bed.gz) BED file refers to CHM13 intervals while the hprc-v1.0-mc-chm13.clipped-intervals.bed.gz BED refers to GRCh38-specific coordinates/intervals. 
Thanks!

**Comment by glennhickey** [comment]
Those are correct.  in the grch38-based graph, no grch38 intervals were clipped out, so you won't see grch38 in its bed file.  likewise for chm13 in the chm13-based graph.
